### ISSUE TITLE
Syntax highlighting aliases, py for python, sh for bash, etc

### ISSUE THREAD

**Issue by Rufflewind** [jgm/highlighting-kate#83]
Most JS-based syntax highlighters accept aliases for various languages, e.g.

    ~~~py
    while True: pass
    ~~~

where `py` is short for `python`.  It would be nice to have something similar for highlighting-kate as well.

In particular, it would be nice to have `sh` as an alias for `bash`.  Although `sh` is often denotes a generic shell, for a syntax highlighter `bash` would do just fine.

**Comment by jgm** [comment]
`py` should work.  Looking at the code (Text/Highlighting/Kate/Syntax.hs):

```
highlightAs lang =
  let lang'  = map toLower lang
      lang'' = if lang' `elem` map (map toLower) languages
                  then lang'
                  else case languageByFullName lang' of
                            Just l -> l
                            Nothing ->
                              case languagesByExtension lang' of
                                    -- go by extension if unambiguous
                                    [l]  -> map toLower l
                                    _    -> lang'
  in  case lang'' of
```

When I tried highlighting-kate directly, it worked:

```
Prelude Text.Highlighting.Kate> highlightAs "python" "x = 3"
[[(NormalTok,"x "),(OperatorTok,"="),(NormalTok," "),(DecValTok,"3")]]
Prelude Text.Highlighting.Kate> highlightAs "py" "x = 3"
[[(NormalTok,"x "),(OperatorTok,"="),(NormalTok," "),(DecValTok,"3")]]
```

Conclusion:  it's pandoc's fault, not highlighting-kate's.

In pandoc, see `src/Text/Pandoc/Highlighting.hs`. The `highlight`
function there needs to figure out which of the class attributes
to use as the language, and it does that by checking for intersection
with the official highligting-kate language names.

Since `py` isn't in that list, `highlightAs` never gets called, even
though it would work fine with `py`!

I think the best solution would be to modify this slightly so that
`lclanguages` contains all the "extensions" as well.

**Comment by Rufflewind** [comment]
Awesome, thanks for the quick fix!
